### ISSUE TITLE
Dataset Problem

### ISSUE THREAD

**Issue by yin-hong** [WindChimeRan/CopyMTL#1]
Hello!
I have some questions about this project.
    Can you share the original dataset? My email is 931558722@qq.com. Thank you
   Do you filter all sentences that contain only the relationship of None?

Thank you!

**Comment by WindChimeRan** [comment]
I use the same dataset with the [official version](https://github.com/xiangrongzeng/copy_re).
The NA relation has been filtered. Moreover, in CopyRE, NA relation has a different meaning, that is, a component of NA triplets, which works as padding.
