### ISSUE TITLE
数据集

### ISSUE THREAD

**Issue by ee2r2fd** [WindChimeRan/CopyMTL#4]
您可以发一下原始的NYT数据集吗？或者链接，2213641681@qq.com  谢谢！

**Comment by WindChimeRan** [comment]
The original NYT is for DSRE. You can download it from [OpenNRE](https://github.com/thunlp/OpenNRE)

And find the preprocessing script in [CopyRE](https://github.com/xiangrongzeng/copy_re/tree/master/data_process/nyt)
