### ISSUE TITLE
Question about multi-token entity in the dataset

### ISSUE THREAD

**Issue by weizhepei** [WindChimeRan/CopyMTL#5]
Hi Haoran, I notice that you directly use the preprocessed datasets released by CopyR [Zeng, 2018] in your experiments. In this [repo](https://github.com/xiangrongzeng/copy_re), I checked their preprocessing scripts and downloaded the datasets. Then I find that they only use the last word to represent the entity in both training and test set. As a consequent, the preprocessed datasets contain no multi-token entity and the annotated triples are all composed of two tokens and one relation type. 

The proposed CopyMTL can conceptually address the multi-token entities problem. However, I wonder whether the adopted dataset is suitable to be the testbed to validate this argument because it doesn't contain any multi-token entities. Could you please explain this issue a little further? Or am I missing anything?  Thank you very much!

**Comment by WindChimeRan** [comment]
Yes. The original dataset in CopyR is not suitable for the multi-token problem.

For the paper, I reprocessed the dataset from scratch to find the whole entity. This includes 1. dataset alignment 2. StandfordNER. Not all sentences can be found in the raw dataset, that's the reason why I use StanfordNER to compensate failed sentences.

This repo only contains CopyRE' part (the magic Eq. 10). MTL part (include my dataset) is very old and messy, we are not going to release it.
