### ISSUE TITLE
模型评价时也仅考虑实体的“最后一个词”吗？

### ISSUE THREAD

**Issue by twjiang** [WindChimeRan/CopyMTL#6]
非常感谢您的工作。该工作可以解决实体词的多词问题，但为什么数据处理和copyRE好像是一样的，即仅仅保留了实体词的最后一个词？这不就违背了论文的初衷吗？？

目前看处理之后的数据都仅仅记录了最后一个词的位置而没有记录初始位置，训练集使用这个没有问题，但测试和开发也这么处理会不会就有问题了？

**Comment by WindChimeRan** [comment]
开源的是和CopyRE直接比较的CopyRE'
CopyMTL没开源。因为数据预处理太粗糙
