### ISSUE TITLE
论文中NovelTagging和GraphRel的结果是只看最后一个token吗？

### ISSUE THREAD

**Issue by fyubang** [WindChimeRan/CopyMTL#8]
![image](https://user-images.githubusercontent.com/25549892/94365047-64efd880-0100-11eb-9939-81df87fbcc2b.png)
Hi，Nice Work。想请教一个问题，我看论文里只说了copyre是less strict，事实上这个表格的NovelTagging和GraphRel，也是只看最后一个token的吧？因为NovelTagging是从copyre粘过来的结果，然后GraphRel是从原文粘过来的（原文说了只看最后一个token），为什么这里只提CopyRE呢？

**Comment by WindChimeRan** [comment]
Yes. I did not reproduce NovelTagging and GraphRel. The results are copied from their paper.
